### ISSUE TITLE
Why is it necessary to load "shenzhen" state dict for GWN? 

### ISSUE THREAD

**Issue by KL4805** [RobinLu1209/ST-GFSL#1]
Dear authors, 

I followed your code and run it with graph-wavenet. In the file `maml.py`, I saw
```
        if self.model_name == 'GWN':
            maml_model = MetaGWN(self.model_args, self.task_args)
            maml_model.load_state_dict(torch.load('shenzhen_gwn_model.pkl'))
            print("model load successfully.")
            maml_model = maml_model.cuda()
```
I wonder why is it necessary to load the state dict, especially for GWN model?

**Comment by RobinLu1209** [comment]
Thank you for your interest in our work. We are very sorry that this is a legacy problem in the code debugging phase, for any model is not needed to load the model. We will comb the code again and update the codebase in the near future.
