### ISSUE TITLE
Why add target dataset when construct the dataset?

### ISSUE THREAD

**Issue by isharrisleung** [RobinLu1209/ST-GFSL#2]
Hello author, thank you for your excellent work. I've been studying your work recently and I've run into some problems that I hope you can help me with. As I said in the title, why in the Meta-Train stage, when constructing the dataset, do you add the target data?
<img width="892" alt="截屏2022-09-01 22 40 42" src="https://user-images.githubusercontent.com/37500344/187942249-7899d092-938e-49dd-93f4-3c26081d543f.png">
After doing this, when Meta-train reads the data, the target data will be randomly obtained, as follows:
<img width="636" alt="截屏2022-09-01 22 43 20" src="https://user-images.githubusercontent.com/37500344/187943074-e61501f2-e318-4a87-83ac-00857c7380a9.png">
I think it leads to the leakage of information of target data. 
Is my point correct? Or maybe I'm missing something and misunderstood your approach. Looking forward to your answer, thank you very much.

**Comment by RobinLu1209** [comment]
Hello, thank you for your attention to our work!
First of all, I want to stress that there is no data leakage problem here. "add_target" is an optional parameter. When it is TRUE, we will only add the few-shot training data in target city (for example, 3-day data for fine-tuning). The specific code is in dataset.py Lines 83 to 107. Therefore, the test data or large scale training data of the target city will not be involved.

**Comment by isharrisleung** [comment]
> Hello, thank you for your attention to our work! First of all, I want to stress that there is no data leakage problem here. "add_target" is an optional parameter. When it is TRUE, we will only add the few-shot training data in target city (for example, 3-day data for fine-tuning). The specific code is in dataset.py Lines 83 to 107. Therefore, the test data or large scale training data of the target city will not be involved.

Oh, I see, looks like I'm missing something. So during the meta train, the few-shot training data in target city can also be used for us because it is available. 
Thanks for your answer and your excellent work.

**Comment by RobinLu1209** [comment]
> > Hello, thank you for your attention to our work! First of all, I want to stress that there is no data leakage problem here. "add_target" is an optional parameter. When it is TRUE, we will only add the few-shot training data in target city (for example, 3-day data for fine-tuning). The specific code is in dataset.py Lines 83 to 107. Therefore, the test data or large scale training data of the target city will not be involved.
> 
> Oh, I see, looks like I'm missing something. So during the meta train, the few-shot training data in target city can also be used for us because it is available. Thanks for your answer and your excellent work.

Yes, that's right! If my work is of any help to you, I would appreciate it if you could cite my paper in your work :)
