### ISSUE TITLE
What are the meanings represented by the 2 feature dimensions in the dataset

### ISSUE THREAD

**Issue by EternityZY** [RobinLu1209/ST-GFSL#4]
Hello author, in your public dataset, the feature dimension of each node in each dataset is 2. It can be seen that the 0th dimension represents speed, so what data does the 1st dimension represent?  Its range of values is [0,1.] .
When predicting, only the speed was predicted, without considering dimension 1.

**Comment by RobinLu1209** [comment]
Hi, the 1st dimension of input data indicate the temporal encoding of time, which is a side information for traffic prediction task.
