### ISSUE TITLE
Transfer the knowledge between graphs with different number of nodes? 

### ISSUE THREAD

**Issue by JingweiZuo** [RobinLu1209/ST-GFSL#5]
Dear authors,

Firstly, I would like to express my gratitude for sharing the code for your wonderful work, which I find quite inspiring.

After thoroughly reading your paper, I have a question regarding the transfer of non-shared parameters to the target city with a graph of different numbers of nodes. While the paper explains the meta-knowledge and the Parameter Generation process in Section 4.2, I am still unclear about how the source and target nodes are aligned. For instance, how the meta-knowledge $Z^{MK} \in R^{N \times d_{MK}}$ can be transferred to the target city with a graph of $N'$ nodes? 

I would be grateful if you could provide clarification on this matter.

Thank you in advance for your time and assistance.

Best regards,
Jingwei

**Comment by RobinLu1209** [comment]
Thanks for your attention. The learned meta-knowledge is node-level, and thereby the node number of different cities is not a matter. The knowledge transfer is achieved by parameter matching. To be specific, if two nodes (either intra-city or inter-city) have the similar meta-knowledge, they will have similar parameters of feature extractor. Therefore, in a novel city with few-shot samples can share the power of feature extraction through a similar nodes in large-scale cities.

**Comment by JingweiZuo** [comment]
Many thanks for your prompt answer. It is clear now :)

**Comment by HQ-LV** [comment]
Thanks for sharing the code！
Could you please tell me where is the specific implementation of the Parameter Generation  in the code?
