### ISSUE TITLE
Which feature extractor do you use to get the result in table2?

### ISSUE THREAD

**Issue by serre20** [RobinLu1209/ST-GFSL#6]
It seems that the feature extractor is not claimed for the results in table2. Should it be graph wavenet (GWN)?
I would be grateful if you could provide clarification on this problem.

**Comment by RobinLu1209** [comment]
In Table 2, we did the ablation study based on GRU feature extractor.

**Comment by serre20** [comment]
Does this imply that the optimal result for ST-GFSL was achieved using GRU as the feature extractor?

**Comment by RobinLu1209** [comment]
Nope, ST-GFSL is a universal framework, which can be combined with any feature extractor.

**Comment by serre20** [comment]
I'm sorry that I fail to clearly clarify my confuse. Of course I know that ST-GFSL is a universal framework. What I mean is which feature extractor is combined with to get the result for ST-GFSL on Table 2?
I believe that you choose the proper feature extractor to make the ST-GFSL achieve the best result.

**Comment by RobinLu1209** [comment]
In Table 2, we directly use GRU model as feature extractor. ST-GFSL shows consistently performance improvement in most feature extractors.

**Comment by serre20** [comment]
Thank you for your patient reply !
