### ISSUE TITLE
Why the result for both MAML(M2) and ST-GFSL different between Table2 and Table3?

### ISSUE THREAD

**Issue by serre20** [RobinLu1209/ST-GFSL#7]
Most of the result are the same between MAML in Table2 and M2 in Table3, is it an accidentally made mistake for the rest differences?
What is more, do you choose a different random seed for ST-GFSL in Table2 and Table3?
I would be grateful if you could provide clarification on this problem.

**Comment by RobinLu1209** [comment]
Apologies for our careless inconsistent issues that may arise in RMSE of (M2) on METR-LA datasets, although the result is quite close. The M2 ablation study in Table 2 use the same model with MAML. We use 10 different seeds to conduct the experiment.

**Comment by serre20** [comment]
Thak you for your reply!
